name: Spark Dynamodb CI

on:
    push:
        branches:
            - 'github-registry-publish' # only run on this branch
        tags:
            - "**" # matches every tags
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '8'
                cache: 'sbt'
            - name: publish
              run: mvn deploy
              env:
                  LOGIN_TOKEN: ${{ secrets.GITHUB_TOKEN }}


